//ADMIN
CREATE USER RESPONSABILE_ADMIN IDENTIFIED BY ADMIN;
GRANT CONNECT, RESOURCE, DBA, to RESPONSABILE_ADMIN;
GRANT ALL PRIVILEGES to RESPONSABILE_ADMIN;

//DIPENDENTE
CREATE USER DIPENDENTE_USER IDENTIFIED BY PASSWORD_DIP;
GRANT CREATE SESSION TO DIEPNDENTE_USER;
GRANT SELECT ON INVENTARIO TO DIPENDENTE_USER;
GRANT SELECT ON TURNO TO DIPENDENTE_USER;

//CLIENTE
CREATE USER CLIENTE IDENTIFIED BY PASSWORD_CLIENTE;
GRANT CONNECT TO CLIENTE;
GRANT CREATE SESSION TO CLIENTE;
GRANT SELECT ON CARTA_FEDELTA;
GRANT EXECUTE ON NUMERO_PROMO_CLIENTE TO CLIENTE;
GRANT EXECUTE ON PUNTI TO CLIENTE;