--Amministratore
CREATE USER AMMINISTRATORE_GENERALE IDENTIFIED BY ADMIN;
GRANT CONNECT, RESOURCE, DBA, TO AMMINISTRATORE_GENERALE;
GRANT ALL PRIVILEGES TO AMMINISTRATORE_GENERALE;

--Segretario
CREATE USER SEGRETARIO IDENTIFIED BY PASS_SEGRETARIO;
GRANT EXECUTE ON Prenotazione_accettata TO SEGRETARIO;
GRANT EXECUTE ON Resoconto_giornata TO SEGRETARIO;
GRANT EXECUTE ON Lavoratori_nel_reparto TO SEGRETARIO;
GRANT EXECUTE ON Turni_personale_medico TO SEGRETARIO;
GRANT INSERT ON Turno_in TO SEGRETARIO;
GRANT INSERT ON Lavora_in TO SEGRETARIO;
GRANT INSERT ON Effettua_turno TO SEGRETARIO;
GRANT INSERT ON Prenotazione TO SEGRETARIO;
GRANT INSERT ON Visitatore TO SEGRETARIO;


--Psichiatra
CREATE USER PSICHIATRA IDENTIFIED BY PASS_PSICHIATRA;
GRANT EXECUTE ON Medicinali_del_paziente TO PSICHIATRA;
GRANT INSERT INTO Diagnostica TO PSICHIATRA;
GRANT INSERT INTO Prescrizione TO PSICHIATRA;


--Psicoterapeuta
CREATE USER PSICOTERAPEUTA IDENTIFIED BY PASS_PSICOTERAPEUTA;
GRANT EXECUTE ON Medicinali_del_paziente TO PSICOTERAPEUTA;
GRANT INSERT ON Seduta TO PSICOTERAPEUTA;


--Infermiere
CREATE USER INFERMIERE IDENTIFIED BY PASS_INFERMIERE;
GRANT EXECUTE ON Medicinali_del_paziente TO INFERMIERE;
GRANT INSERT ON Somministra TO INFERMIERE;


--Medico
CREATE USER MEDICO IDENTIFIED BY PASS_MEDICO;
GRANT EXECUTE ON Medicinali_del_paziente TO MEDICO;
GRANT EXECUTE ON Ricovero_in_infermieria TO MEDICO;
GRANT INSERT ON Effettua_ck TO MEDICO;
GRANT INSERT ON Check_Up TO MEDICO;

